apiVersion: v1
kind: Secret
metadata:
  name: pf9-s3-secret
  namespace: s3-monitoring-bot
data:
  aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
  aws_secret_access_key: {{ .Values.aws.aws_secret_access_key | b64enc | quote }}
